### ISSUE TITLE
Sheet background does not respect app's theme

### ISSUE THREAD

**Issue by SylarRuby** [mtj0928/ResizableSheet#9]
Hola. Thanks for provide the community with such an elegant sheet. No major issues, just something I've noticed.

The sheet's background changes when the system's theme changes: dark mode gives the sheet a dark color and light mode... white sheet. Apps can specify a theme in which the sheet does not respect. An example how an app could change the theme:

```swift
class Utilities: ObservableObject {

    // The default is to use the system's default.
    @AppStorage("theme") var theme: String = ""
    
    var userInterfaceStyle: ColorScheme? = .dark

    func overrideDisplayMode() {
        var userInterfaceStyle: UIUserInterfaceStyle

        if theme == "On" {
            userInterfaceStyle = .dark
        } else if theme == "Off" {
            userInterfaceStyle = .light
        } else {
            userInterfaceStyle = .unspecified
        }
        
        let scenes = UIApplication.shared.connectedScenes
        let windowScene = scenes.first as? UIWindowScene
        let window = windowScene?.windows.first
        
        window?.overrideUserInterfaceStyle = userInterfaceStyle
    }
}
```
Should the system is set to dark mode and the app to light, the content sheet's background is still dark. Ok I could use the `.sheetBackground` modifier you've provided us, with a combination with `@Environment(\.colorScheme) var colorScheme`. Seems a bit messy if we have many sheets within the app. Is there a way to make the sheet respect the app's theme? I'd rather not having to keep repeating this:

```swift
view.resizableSheet($state) { builder in
            builder.content { context in
                VStack {
                    Text("Demo")
                    Spacer()
                }
                    .padding()
                    .frame(height: 300)
            }.sheetBackground { _ in
                Color(colorScheme == .light ? "custom-white" : "custom-secondary")
            }
        }

```

**Comment by mtj0928** [comment]
@SylarRuby 
Thank you for your report!!

I didn't notice the issue.
ResizableSheet creates a new window, but the window's overrideUserInterfaceStyle is not updated on your code.
I will add a new api to control the window soon.

As a workaround, you can specify color theme for all windows in windowScene like this.
```swift
let scenes = UIApplication.shared.connectedScenes
let windowScene = scenes.first as? UIWindowScene
windowScene?.windows.forEach({ window in
    window.overrideUserInterfaceStyle = userInterfaceStyle
})
```

**Comment by SylarRuby** [comment]
Hi @mtj0928 No problem and that workaround works just fine. Thank you!

**Comment by mtj0928** [comment]
@SylarRuby I updated the API.

From 0.0.4, you can access `window` in ResizableSheetCenter via a static method.

```swift
let window = ResizableSheetCenter.resolve(for: windowScene)?.window

// you can update the window  here
window?.overrideUserInterfaceStyle = userInterfaceStyle
```

**Comment by SylarRuby** [comment]
Thank you!
